### ISSUE TITLE
Wrong extension inside package.json

### ISSUE THREAD

**Issue by s1mpleTEK** [adonisjs/.github#8]
### Package version

/

### Describe the bug

Currently in the `package.json`, all the extensions are `.js` inside scripts and imports while all the files in the repo are `.ts`, which causes an error when running `npm start`.

**Comment by RomainLanz** [comment]
Hey @s1mpleTEK! 👋🏻 

This is how it is supposed to work.

If you want to run in development your server, use `npm run dev`, `npm run start` is for production.
